all:
	make -C test-00-bootstrap
	make -C test-01-stack
	make -C test-03-pointer
	make -C test-04-static
	make -C test-98-FibonacciElement
	make -C test-99-StaticsTest
	make -C test-ssa2asm-00-store_imm
	make -C test-ssa2asm-01-subroutine
	make -C test-ssa2asm-02-arithmetic
	make -C test-ssa2asm-03-branching
	make -C test-ssa2asm-04-arguments
clean:
	make -C test-00-bootstrap clean
	make -C test-01-stack clean
	make -C test-03-pointer clean
	make -C test-04-static clean
	make -C test-98-FibonacciElement clean
	make -C test-99-StaticsTest clean
	make -C test-ssa2asm-00-store_imm clean
	make -C test-ssa2asm-01-subroutine clean
	make -C test-ssa2asm-02-arithmetic clean
	make -C test-ssa2asm-03-branching clean
	make -C test-ssa2asm-04-arguments clean
