all:
	make -C test-00-bootstrap
	make -C test-01-stack
	make -C test-03-pointer
	make -C test-04-static
	make -C test-98-FibonacciElement
	make -C test-99-StaticsTest
clean:
	make -C test-00-bootstrap clean
	make -C test-01-stack clean
	make -C test-03-pointer clean
	make -C test-04-static clean
	make -C test-98-FibonacciElement clean
	make -C test-99-StaticsTest clean
