sudo: false
language: cpp
os: linux
dist: trusty
script: apt-cache search libsigc++; CXX=clang++-6.0 tools/build.sh
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-6.0
      - cmake
      - g++-7
      - libboost-dev
      - libgtkmm-3.0-dev
