sudo: false
language: cpp
compiler: gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: tools/build.sh
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-4.8
      - gcc-4.8
      - libboost-dev
      - libgtkmm-3.0-dev
